dist: focal
language: python

python:
  - "3.10"
  - "3.13"

env:
  global:
    - DJANGO_SETTINGS_MODULE=mysite.settings

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

before_script:
  - cd mysite
  - python manage.py migrate

script:
  - black --check .
  - flake8
  - coverage run --source=mysite manage.py test
  - coverage report

deploy:
  provider: elasticbeanstalk
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-2
  app: mysite-polls
  env: polls-env
  bucket_name: elasticbeanstalk-us-east-2-340752796349
  bucket_path: "mysite"
  on:
    all_branches: true 


before_script:
  - cd mysite
  - python manage.py migrate

script:
  - black --check .
  - flake8
  - coverage run --source=mysite manage.py test
  - coverage report

after_success:
  - coveralls